// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserManager.Application.API.Data.Contexts;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(UserManagerDbContext))]
    [Migration("20231201222614_InitialwithData")]
    partial class InitialwithData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Common.DTOs.UserDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd1478e7-b80f-b009-03ca-0fa5ffffb0ef"),
                            Age = 34,
                            City = "Hilarioport",
                            Email = "Kameron.Stark@gmail.com",
                            FirstName = "Xzavier",
                            LastName = "Watsica",
                            State = "Montana",
                            StreetAddress = "93419 Kling Course",
                            ZipCode = "97935-5424"
                        },
                        new
                        {
                            Id = new Guid("6175556d-0a49-cce4-3882-e67f2e5e58d4"),
                            Age = 69,
                            City = "West Mike",
                            Email = "Buford.Beatty@gmail.com",
                            FirstName = "Afton",
                            LastName = "Hoppe",
                            State = "New Jersey",
                            StreetAddress = "954 Fisher Isle",
                            ZipCode = "35087"
                        },
                        new
                        {
                            Id = new Guid("35d841c5-6d58-e772-9f7c-ae9a83259277"),
                            Age = 48,
                            City = "North Ali",
                            Email = "Stacy8@hotmail.com",
                            FirstName = "Maryam",
                            LastName = "McGlynn",
                            State = "West Virginia",
                            StreetAddress = "69926 Tate Unions",
                            ZipCode = "79693-4502"
                        },
                        new
                        {
                            Id = new Guid("de22317e-3ef8-ad2f-24bd-76256ddc6b85"),
                            Age = 68,
                            City = "Watsicaberg",
                            Email = "Dale.Hegmann56@hotmail.com",
                            FirstName = "Antwon",
                            LastName = "Smith",
                            State = "South Carolina",
                            StreetAddress = "030 Sabrina Tunnel",
                            ZipCode = "14718-7981"
                        },
                        new
                        {
                            Id = new Guid("10e3548d-402e-61d7-e92b-521149b3d45d"),
                            Age = 82,
                            City = "West Jeromyfurt",
                            Email = "Angeline_Boyer@hotmail.com",
                            FirstName = "Rollin",
                            LastName = "Moore",
                            State = "Minnesota",
                            StreetAddress = "85628 Harris Village",
                            ZipCode = "97088-1000"
                        },
                        new
                        {
                            Id = new Guid("24d30425-5188-fa7a-ee41-6783149374ee"),
                            Age = 58,
                            City = "Conroyside",
                            Email = "Hollis_Waelchi18@gmail.com",
                            FirstName = "Arnoldo",
                            LastName = "Pfeffer",
                            State = "Mississippi",
                            StreetAddress = "03219 Wisoky Summit",
                            ZipCode = "48784"
                        },
                        new
                        {
                            Id = new Guid("e50f5076-2549-e2cd-9e32-2878669d6adb"),
                            Age = 32,
                            City = "Claudineburgh",
                            Email = "Daija53@gmail.com",
                            FirstName = "Jovanny",
                            LastName = "Pollich",
                            State = "Wisconsin",
                            StreetAddress = "074 Eino Terrace",
                            ZipCode = "42019-5037"
                        },
                        new
                        {
                            Id = new Guid("0187f608-f85a-9e4d-817f-724059d9f62d"),
                            Age = 67,
                            City = "Uptonmouth",
                            Email = "Tracy59@gmail.com",
                            FirstName = "Freida",
                            LastName = "Wilderman",
                            State = "Mississippi",
                            StreetAddress = "5069 Clementina Trail",
                            ZipCode = "23448"
                        },
                        new
                        {
                            Id = new Guid("e1ebca6d-8474-114a-74ac-88baaf381368"),
                            Age = 64,
                            City = "West Amyhaven",
                            Email = "Asha.Schmidt@yahoo.com",
                            FirstName = "Ronaldo",
                            LastName = "Spencer",
                            State = "New Mexico",
                            StreetAddress = "04962 Wunsch Lakes",
                            ZipCode = "85956-3574"
                        },
                        new
                        {
                            Id = new Guid("8afbd162-4b71-56f6-f15e-6642c02cd9ca"),
                            Age = 42,
                            City = "Lake Pinkton",
                            Email = "Felicity87@yahoo.com",
                            FirstName = "Aubrey",
                            LastName = "D'Amore",
                            State = "North Carolina",
                            StreetAddress = "93591 Stehr Hollow",
                            ZipCode = "69545"
                        },
                        new
                        {
                            Id = new Guid("b72c6117-a1fd-cb15-950b-a9ee3f57689e"),
                            Age = 77,
                            City = "Allanton",
                            Email = "Vance_Thiel@hotmail.com",
                            FirstName = "Jarod",
                            LastName = "Rowe",
                            State = "Alaska",
                            StreetAddress = "65070 Ryan Meadows",
                            ZipCode = "49896"
                        },
                        new
                        {
                            Id = new Guid("c0a95dae-4099-4e11-f8ee-c87067aa014a"),
                            Age = 67,
                            City = "East Xzavierfort",
                            Email = "Brain17@hotmail.com",
                            FirstName = "Niko",
                            LastName = "Mosciski",
                            State = "Mississippi",
                            StreetAddress = "497 Daren Neck",
                            ZipCode = "41458"
                        },
                        new
                        {
                            Id = new Guid("21fe6ecb-46ab-962d-21a5-e3dac9ca3add"),
                            Age = 27,
                            City = "Davisbury",
                            Email = "Mariah6@hotmail.com",
                            FirstName = "Jennie",
                            LastName = "Jaskolski",
                            State = "Indiana",
                            StreetAddress = "63899 Paucek Bypass",
                            ZipCode = "65682-5022"
                        },
                        new
                        {
                            Id = new Guid("fa557abc-8680-d52a-062c-cf790b057d6e"),
                            Age = 57,
                            City = "Lake Maximofort",
                            Email = "Filiberto_Morar34@gmail.com",
                            FirstName = "Colleen",
                            LastName = "Schultz",
                            State = "New Jersey",
                            StreetAddress = "5502 Favian Ford",
                            ZipCode = "73729"
                        },
                        new
                        {
                            Id = new Guid("2af1a251-2bd2-1416-80ef-a5922214fcae"),
                            Age = 27,
                            City = "East Heber",
                            Email = "Maud.Walsh7@hotmail.com",
                            FirstName = "Levi",
                            LastName = "Effertz",
                            State = "Utah",
                            StreetAddress = "8325 D'Amore Grove",
                            ZipCode = "02689-6735"
                        },
                        new
                        {
                            Id = new Guid("9b532d58-0a55-cca7-9f21-29142492799d"),
                            Age = 97,
                            City = "North Izaiah",
                            Email = "Connie.Towne@gmail.com",
                            FirstName = "Brad",
                            LastName = "Fay",
                            State = "Georgia",
                            StreetAddress = "23651 Brendon Parks",
                            ZipCode = "70164-8308"
                        },
                        new
                        {
                            Id = new Guid("c3186edc-6765-7dd2-2581-e2a171993eba"),
                            Age = 64,
                            City = "Lake Antoinette",
                            Email = "Velma.Waelchi40@hotmail.com",
                            FirstName = "Denis",
                            LastName = "Goodwin",
                            State = "Massachusetts",
                            StreetAddress = "50066 Chasity Port",
                            ZipCode = "86975-7488"
                        },
                        new
                        {
                            Id = new Guid("97098b68-4e3a-beb5-3263-6555b98477be"),
                            Age = 23,
                            City = "Parisview",
                            Email = "Cydney_Kautzer@hotmail.com",
                            FirstName = "Joyce",
                            LastName = "Rath",
                            State = "Tennessee",
                            StreetAddress = "70407 Kasandra Village",
                            ZipCode = "14428-8392"
                        },
                        new
                        {
                            Id = new Guid("5fc858b7-776b-7983-648e-60f1f76ab48a"),
                            Age = 53,
                            City = "East Malinda",
                            Email = "Velma_Schuster@gmail.com",
                            FirstName = "Buford",
                            LastName = "Bernhard",
                            State = "Vermont",
                            StreetAddress = "7469 Bailee Springs",
                            ZipCode = "90698-9632"
                        },
                        new
                        {
                            Id = new Guid("0e3e9f9e-59e3-3568-edad-f720e965d029"),
                            Age = 29,
                            City = "North Mose",
                            Email = "Victor.Toy@hotmail.com",
                            FirstName = "Hoyt",
                            LastName = "Douglas",
                            State = "Mississippi",
                            StreetAddress = "797 Jarred Walks",
                            ZipCode = "64561-8961"
                        },
                        new
                        {
                            Id = new Guid("2f020d38-892f-9eac-91e0-c5d102b7cf4d"),
                            Age = 88,
                            City = "D'Amorebury",
                            Email = "Sherman.Ortiz@hotmail.com",
                            FirstName = "Dion",
                            LastName = "Carter",
                            State = "Vermont",
                            StreetAddress = "9479 Kellie Summit",
                            ZipCode = "06953"
                        },
                        new
                        {
                            Id = new Guid("e5116f06-fc57-0438-141f-0fec8b721d6e"),
                            Age = 41,
                            City = "Schoenhaven",
                            Email = "Chelsea_Bechtelar25@gmail.com",
                            FirstName = "Harold",
                            LastName = "Schowalter",
                            State = "Kentucky",
                            StreetAddress = "70790 Nolan Court",
                            ZipCode = "89371-3318"
                        },
                        new
                        {
                            Id = new Guid("849a7061-fd34-fdee-a646-d93364480181"),
                            Age = 80,
                            City = "Ciarashire",
                            Email = "Domenico.Larkin86@hotmail.com",
                            FirstName = "Leda",
                            LastName = "Simonis",
                            State = "Arkansas",
                            StreetAddress = "792 Howell Greens",
                            ZipCode = "86554-2851"
                        },
                        new
                        {
                            Id = new Guid("1a7b3f50-d830-2680-03ef-ece3d12ec90d"),
                            Age = 100,
                            City = "Rileychester",
                            Email = "Consuelo22@yahoo.com",
                            FirstName = "Garret",
                            LastName = "Powlowski",
                            State = "Utah",
                            StreetAddress = "38914 Lance Point",
                            ZipCode = "90661-8012"
                        },
                        new
                        {
                            Id = new Guid("dcce889e-16b2-f64f-3e20-591a4a8c54bf"),
                            Age = 74,
                            City = "West Cielo",
                            Email = "Gabrielle_Spinka@yahoo.com",
                            FirstName = "Adrien",
                            LastName = "Littel",
                            State = "Arizona",
                            StreetAddress = "7350 Adan Trail",
                            ZipCode = "21548-5117"
                        },
                        new
                        {
                            Id = new Guid("800b0e2f-3568-7d8c-b138-578dac02c48f"),
                            Age = 71,
                            City = "South Jaron",
                            Email = "Talia97@hotmail.com",
                            FirstName = "Lawson",
                            LastName = "Pfannerstill",
                            State = "Hawaii",
                            StreetAddress = "591 Gregoria Vista",
                            ZipCode = "69161-6668"
                        },
                        new
                        {
                            Id = new Guid("4c6bc1d2-939a-6881-c411-56a8aecf77c9"),
                            Age = 76,
                            City = "North Janetside",
                            Email = "Hilbert71@yahoo.com",
                            FirstName = "Nikolas",
                            LastName = "Kreiger",
                            State = "Tennessee",
                            StreetAddress = "20265 McGlynn Squares",
                            ZipCode = "00260"
                        },
                        new
                        {
                            Id = new Guid("301c0c32-ff0e-0796-0bd6-b2000d905d2f"),
                            Age = 40,
                            City = "Guadalupebury",
                            Email = "Jerry64@gmail.com",
                            FirstName = "Mandy",
                            LastName = "Crist",
                            State = "Massachusetts",
                            StreetAddress = "86780 Bette Inlet",
                            ZipCode = "36585-3336"
                        },
                        new
                        {
                            Id = new Guid("706cc3c5-f9c6-e009-929c-66196ff42991"),
                            Age = 77,
                            City = "East Noeliashire",
                            Email = "Zola.Lebsack6@gmail.com",
                            FirstName = "Kiel",
                            LastName = "Rohan",
                            State = "Indiana",
                            StreetAddress = "45507 Novella Landing",
                            ZipCode = "12576"
                        },
                        new
                        {
                            Id = new Guid("cb16fed1-32ae-80ba-13c9-cc3f3473df94"),
                            Age = 32,
                            City = "New Emely",
                            Email = "Fannie_Kassulke@yahoo.com",
                            FirstName = "Liam",
                            LastName = "Lesch",
                            State = "New Mexico",
                            StreetAddress = "16773 Lane Roads",
                            ZipCode = "37933"
                        },
                        new
                        {
                            Id = new Guid("3682a428-d7f5-33b3-fbbf-0949d4545a36"),
                            Age = 48,
                            City = "North Enochton",
                            Email = "Leland.Lynch@yahoo.com",
                            FirstName = "Santino",
                            LastName = "Boyle",
                            State = "Maryland",
                            StreetAddress = "3887 Bria Orchard",
                            ZipCode = "32393"
                        },
                        new
                        {
                            Id = new Guid("fa849768-f01f-4ea3-bd18-2e18994490a7"),
                            Age = 37,
                            City = "Port Amie",
                            Email = "Camryn45@gmail.com",
                            FirstName = "Quincy",
                            LastName = "Predovic",
                            State = "North Carolina",
                            StreetAddress = "18989 Frami Camp",
                            ZipCode = "96882-9048"
                        },
                        new
                        {
                            Id = new Guid("14d61416-5880-d8e2-a5cf-28663cfda9de"),
                            Age = 51,
                            City = "Rosenbaumstad",
                            Email = "Asa70@gmail.com",
                            FirstName = "Raymond",
                            LastName = "Prohaska",
                            State = "Wisconsin",
                            StreetAddress = "1943 Ankunding Bypass",
                            ZipCode = "09229"
                        },
                        new
                        {
                            Id = new Guid("b0e8823e-7053-cf7b-7491-0c740062c29d"),
                            Age = 82,
                            City = "Leschstad",
                            Email = "Margaret_Aufderhar96@hotmail.com",
                            FirstName = "Shania",
                            LastName = "Kertzmann",
                            State = "South Carolina",
                            StreetAddress = "64518 Lenna Brooks",
                            ZipCode = "21307-4733"
                        },
                        new
                        {
                            Id = new Guid("adcd65bb-f784-e2d8-b1e5-c866f89c5d94"),
                            Age = 87,
                            City = "Ocieside",
                            Email = "Nash_Moen73@hotmail.com",
                            FirstName = "Nettie",
                            LastName = "Lynch",
                            State = "Colorado",
                            StreetAddress = "047 Metz Throughway",
                            ZipCode = "21998-1651"
                        },
                        new
                        {
                            Id = new Guid("5a3b33f3-bc4c-82fb-c2fe-4f80b087d04e"),
                            Age = 60,
                            City = "Watsicastad",
                            Email = "Clare.Hartmann@hotmail.com",
                            FirstName = "Jody",
                            LastName = "Quigley",
                            State = "Delaware",
                            StreetAddress = "2770 Hobart Mall",
                            ZipCode = "46944-7934"
                        },
                        new
                        {
                            Id = new Guid("9bcd109c-7eb8-2a45-4941-1e1578451136"),
                            Age = 35,
                            City = "Rosalindaside",
                            Email = "Reece_Breitenberg8@hotmail.com",
                            FirstName = "Sadye",
                            LastName = "Mante",
                            State = "Kansas",
                            StreetAddress = "20306 Wilfredo Street",
                            ZipCode = "09992"
                        },
                        new
                        {
                            Id = new Guid("f4090f9c-fd6c-3f10-0edb-63883b430148"),
                            Age = 39,
                            City = "Orrinbury",
                            Email = "Gail72@yahoo.com",
                            FirstName = "Queenie",
                            LastName = "Nienow",
                            State = "New Hampshire",
                            StreetAddress = "66873 Welch Path",
                            ZipCode = "62010"
                        },
                        new
                        {
                            Id = new Guid("8438eaaa-2fc2-a406-eaa1-ae1e2fdb3a14"),
                            Age = 70,
                            City = "West Benedict",
                            Email = "William_Thompson@yahoo.com",
                            FirstName = "Brisa",
                            LastName = "Tromp",
                            State = "Idaho",
                            StreetAddress = "682 Ondricka Causeway",
                            ZipCode = "34303"
                        },
                        new
                        {
                            Id = new Guid("5923b62f-081e-c694-1038-372d3a657ff5"),
                            Age = 65,
                            City = "New Julian",
                            Email = "Gerhard15@hotmail.com",
                            FirstName = "Carlos",
                            LastName = "Conn",
                            State = "Oklahoma",
                            StreetAddress = "833 Eryn Port",
                            ZipCode = "64107"
                        },
                        new
                        {
                            Id = new Guid("74cbadd6-f89a-35e6-e95c-505950959399"),
                            Age = 100,
                            City = "Donaldport",
                            Email = "Linnea_Bogisich58@hotmail.com",
                            FirstName = "Roger",
                            LastName = "Fahey",
                            State = "Montana",
                            StreetAddress = "174 Hazle Gardens",
                            ZipCode = "01044"
                        },
                        new
                        {
                            Id = new Guid("633737c1-2475-189a-a374-f8702c44678d"),
                            Age = 85,
                            City = "Kulasstad",
                            Email = "Irma_Stanton28@yahoo.com",
                            FirstName = "Rosamond",
                            LastName = "Bauch",
                            State = "Missouri",
                            StreetAddress = "354 Fahey Fields",
                            ZipCode = "33368-3107"
                        },
                        new
                        {
                            Id = new Guid("35c1727c-2b06-f333-3f72-873bf1c2b2ae"),
                            Age = 57,
                            City = "South Orie",
                            Email = "Idell.Wolf@yahoo.com",
                            FirstName = "Tierra",
                            LastName = "O'Connell",
                            State = "Missouri",
                            StreetAddress = "8150 Tromp Isle",
                            ZipCode = "63128"
                        },
                        new
                        {
                            Id = new Guid("c2c19439-3eb2-9975-0305-ac0e4c3184a1"),
                            Age = 82,
                            City = "Handchester",
                            Email = "Hilton_McKenzie@gmail.com",
                            FirstName = "Gaylord",
                            LastName = "Bruen",
                            State = "Wyoming",
                            StreetAddress = "5962 Emard Flat",
                            ZipCode = "82079-3070"
                        },
                        new
                        {
                            Id = new Guid("9e34d92a-d8ed-0605-e1e4-35986624e9fe"),
                            Age = 47,
                            City = "Botsfordland",
                            Email = "Zelda.Koepp60@yahoo.com",
                            FirstName = "Easter",
                            LastName = "Nicolas",
                            State = "North Carolina",
                            StreetAddress = "81417 Rohan Creek",
                            ZipCode = "95911-9484"
                        },
                        new
                        {
                            Id = new Guid("fb2c08e7-9eac-c54e-6573-4fe3d0127d46"),
                            Age = 47,
                            City = "Loyalmouth",
                            Email = "Duncan_Kertzmann18@hotmail.com",
                            FirstName = "Grant",
                            LastName = "Bartoletti",
                            State = "Connecticut",
                            StreetAddress = "176 Trevion Shore",
                            ZipCode = "17205"
                        },
                        new
                        {
                            Id = new Guid("bd2fcac5-e8d9-70f2-4810-0224f0a735bc"),
                            Age = 45,
                            City = "Spencerville",
                            Email = "Sofia5@hotmail.com",
                            FirstName = "Jarrod",
                            LastName = "Brown",
                            State = "New Mexico",
                            StreetAddress = "88072 Cormier Lodge",
                            ZipCode = "27074-4293"
                        },
                        new
                        {
                            Id = new Guid("1948aa92-d588-dabd-981b-b19a8af47602"),
                            Age = 49,
                            City = "Feltonshire",
                            Email = "Dahlia2@hotmail.com",
                            FirstName = "Pietro",
                            LastName = "Lynch",
                            State = "Massachusetts",
                            StreetAddress = "879 Ryleigh Plaza",
                            ZipCode = "36871"
                        },
                        new
                        {
                            Id = new Guid("70e448a5-87e4-af98-30b2-62e26261cb48"),
                            Age = 93,
                            City = "New Destineychester",
                            Email = "Astrid_Blanda@hotmail.com",
                            FirstName = "Peggie",
                            LastName = "Parisian",
                            State = "Mississippi",
                            StreetAddress = "000 Gulgowski Plains",
                            ZipCode = "20494-3930"
                        },
                        new
                        {
                            Id = new Guid("ea78cf86-e94b-9570-c553-00e5bb7c4d0b"),
                            Age = 18,
                            City = "West Colleenmouth",
                            Email = "Minnie82@yahoo.com",
                            FirstName = "Daphney",
                            LastName = "Klocko",
                            State = "Oklahoma",
                            StreetAddress = "85084 VonRueden Station",
                            ZipCode = "80291"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
